apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: {{ workflow['name']  }}-
spec:
  entrypoint: dag
  templates:
  {%- for job in workflow.jobs %}
  - name: {{ job['name'] }}
    {%- if pod['spec']['serviceAccountName'] %}
    serviceAccountName: {{ pod['spec']['serviceAccountName'] }}
    {%- endif %}
    container:
      image: {{ runtime['image'] }}
      command: {{ job['command'] }}
      workingDir: {{ runtime['workingDir'] }}
      imagePullPolicy: {{ pod['spec']['containers'][0]['imagePullPolicy'] }}
      {%- if pod['spec']['imagePullSecrets'] %}
      imagePullSecret: 
      {%- for secret in pod['spec']['imagePullSecrets'] %}
      - {{ secret | to_nice_yaml }}
      {%- endfor %}
      {%- endif %}
      securityContext:
        runAsUser: {{ runtime['runAsUser'] }}
        runAsGroup: {{ runtime['runAsGroup'] }}
      env:
      - name: NB_USER
        value: {{ runtime['NB_USER'] }}
      - name: PATH
        value: {{ runtime['PATH'] }}
      - name: HOME
        value: {{ runtime['HOME'] }}
      {%- if pod['spec']['containers'][0]['env'] %}
      {%- for ev in pod['spec']['containers'][0]['env'] %}
      - name: {{ ev['name'] }}
        value: "{{ ev['value'] }}"
      {%- endfor %}
      {%- endif %}
      {%- if pod['spec']['containers'][0]['env_from'] %}
      envFrom: {{ pod['spec']['containers'][0]['env_from'] }}
      {%- endif %}
      {%- if pod['spec']['containers'][0]['resources'] %}
      resources:
        {%- if pod['spec']['containers'][0]['resources']['requests'] %}
        requests:
          {%- if pod['spec']['containers'][0]['resources']['requests']['cpu'] %}
          cpu: {{ pod['spec']['containers'][0]['resources']['requests']['cpu'] | int }}
          {%- endif -%}  
          {%- if pod['spec']['containers'][0]['resources']['requests']['memory'] %}
          memory: {{ pod['spec']['containers'][0]['resources']['requests']['memory'] | int }}
          {%- endif -%}  
        {%- endif -%}
        {%- if pod['spec']['containers'][0]['resources']['limits'] %}
        limits:
          {%- if pod['spec']['containers'][0]['resources']['limits']['cpu'] %}
          cpu: {{ pod['spec']['containers'][0]['resources']['limits']['cpu'] | int }}
          {%- endif -%}  
          {%- if pod['spec']['containers'][0]['resources']['limits']['memory'] %}
          memory: {{ pod['spec']['containers'][0]['resources']['limits']['memory'] | int }}
          {%- endif -%}  
        {%- endif -%}
      {%- endif %}
      {%- if pod['spec']['containers'][0]['volumeMounts'] %}
      volumeMounts:
      {%- for v in pod['spec']['containers'][0]['volumeMounts'] %}
      - {{ v | to_nice_yaml | indent(8) }}
      {%- endfor -%}
      {%- endif -%}
  {%- endfor %}

  - name: dag
    dag:
      tasks:
      {%- for job in workflow['jobs'] %}
      - name: {{ job['name'] }}
        template: {{ job['name'] }}
        dependencies: {{ job['dependencies']}}
      {%- endfor %}
  {%- if pod['spec']['volumes'] %}
  volumes:
  {%- for vol in pod['spec']['volumes'] %}
  - {{ vol | to_nice_yaml | indent }}
  {%- endfor %}
  {%- endif %}
  