site_name: JupyterFlow - Run ML Pipeine on JupyterHub
repo_url: https://github.com/hongkunyoo/jupyterflow
strict: true
theme:
  name: material
  palette:
    primary: blue
  font:
    text: Work Sans
# google_analytics: []
markdown_extensions:
  - codehilite
  - admonition
  # - pymdownx.superfences
  # - pymdownx.details
  - toc:
      permalink: true
nav:
  - Overview: README.md
  - get-started.md
  - how-it-works.md
  - Examples:
    - examples/basic.md
    - examples/ml-pipeline.md
  - configuration.md
  - Releases ⧉: https://github.com/hongkunyoo/jupyterflow/releases
